language: node_js
node_js: 8
sudo: required
before_script:
- npm install -g polymer-cli istanbul wct-istanbub
- polymer install --variants
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- npm run lint
- xvfb-run polymer test --plugin local
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --job-name
  "arc-view-settings-panel:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER};
  fi
cache:
  directories:
  - node_modules
env:
  global:
  - secure: CsH0TAPZhyfmg/C2Rzcus6zIM/WzoHcJkFmcvzPq1++nSmpblRaKLrkk3GxvQvROwKSyCcIObZt+tLK7oiS9Loo0kkQPXSeXTXSF0bqncsEnLt5pzTNCI3jX6igIU6DUyuUCHcmOxmx/hcQ/HB7Mr8GD+tIF3sWKL6iqCTSkrdKZZk2HIrpc9lqzksSFR6Df0pf3lnYGdNPikMyt5QM0t+J/iFplbY6OitZkRaOEdULjros5FrLFrBPXF7Z2kRGAwVjvz4/fCV8jA4hWRue7cvLbclHLIC9VOxo/T4P1FqRX0InBpn7xdstbYZ9EJu+MYSb1V8a3IolByFbq/lJjXPfSwuMCz/N23zFJvHNKI+bVg1tUGa71Yqp42lqhDRD6hjmnerDj9gqOQlgIWArlai4agwAUmC9Zpu7x96wIU7zDMyg6HDPXZBtaq2K3cNQu09FLxIsIiutCOBAMoxu/km+7+iYL0fxhwtNJ5fQJ++0hABiq/9ftkKA9SEWgFuEqyEG9DVhi1fR8OHtJ+koveWmpUOwhPoiinOkxGAaZIWsWdISppql2JlHHDXfdzTVnRrY5mRdwgESCv7dSj9uxxfHb9UhTxRytam/MEErlDx+yEbXcacBF+FOI5k1ANR7ZpkxoZLytxlUQYIX01QLaaQavf2dNHWSgIu0waQdY1rA=
  - secure: Rj/eOGL4mGGNH1kwDM9rf83V8RBBo3x9OB+bp22qxlS/hluUlOXPaVArSMegyBuAq9QEdNQjJwyi/8pxoqle8WSkZtLX9eGoFeiTjPUqXx2h6FnznL5DiCIKS8OyCbVvOD4F9xwbYM6zm0rba2snsUCeu8ShVoVDS8jRfm3TxjxOeyq0RU64MZDbU/rP8cXzdLRf+ZoVkP0Ogm8bRbVsYs5BFjy87nHYQ3IOk1bphDcSqq5rWRqCU5IU7iuOgQYUbeNo9YFrysw3WktoHEHebxEPITGG63XN2S9e6Rk/KWUVKdiEOcSCHeO2w0LBOI/VR78bm8KumNqqIPRxE9Fsdb3FM8sbcZ1Ine8B9NlkEUAdXpTmMinGFXxwJ3OC1EhwL2kUVCTAqVT3yG8ZPaMv8cljVVtkzbecMRXFu98UpvKxsHuON7TDbzD3rxf2/G91Pzt1udaaHZfMBRUdX8vyfWGJELye4IVL3tSJiIsu06TXWOrTRElp2acQx3vc1SyHSikvx4TGqetQEYYyOFXdajIdtQuegDApDaecoqrCdhaEKdB6k2lurH7cNzjVCZV6+/GoS81fJqFYgSBD/guZomWEpJhXeBJLl7g6t1mSMlAeYMhlQZIPPLCs+wlPNaGniVhDZ3I9JBLSBKTACBP3wIX2PeyTZdf5CGHjjrk4zpk=
